cloud:
  aws:
    credentials:
      access-key: AKIAXYBURX5SCZYVKA2B
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: sonmabu-bucket


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 20MB
      max-file-size: 50MB
      max-request-size: 100MB
